### ISSUE TITLE
Project setup version control instructions

### ISSUE THREAD

**Issue by awdeorio** [eecs280staff/tutorials#11]
The Setup section in P2 - P5 places the version control set up before the starter files setup.  In the version control tutorial, it says "We’re assuming that you already have a folder with starter source code in it".  That's a contradiction.

Furthermore, we could do a better job of specifying which steps should be completed by the first partner (create) and which steps should be completed by the second partner (clone).

To be clear, nothing is wrong with the version control tutorial itself.  The project specs just need to be consistent with the existing version control tutorial.

## Todo
- [x] Update P2 Setup section https://github.com/eecs280staff/p2-cv/pull/186
- [x] Update P3 Setup section https://github.com/eecs280staff/p3-euchre/pull/186
- [x] Update P4 Setup section
- [x] Update P5 Setup section
