### ISSUE TITLE
Command line cheat sheet

### ISSUE THREAD

**Issue by awdeorio** [eecs280staff/tutorials#24]
It would be nice to provide a Linux command line cheat sheet that contains all the commands used in the setup tutorial.

For reference, here's a [past](https://github.com/eecs280staff/eecs280.org/files/5489780/Command_line_tools.pdf) cheat sheet.

## TODO
- [ ] Draft a cheat sheet in Markdown
- [ ] Verify that each command from the setup tutorial appears in the cheat sheet
- [ ] Edit for length, should be 1 page
- [ ] Link from eecs280.org Tutorials section
- [ ] Link from setup tutorial
